title: How To Improve Dota MMR
author: @GilVengeance
email: gilbrankha1132@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  in this blog. i will help you to improve your mmr

# social links
twitter_username: GHaythami # DO NOT include the @ character, or else the build will fail!
github_username:  GilVengeance # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
